name: qt5-qml-application
version: "2"
summary: Qt5 Application Example
description: A simple text editor
grade: stable
confinement: strict
base: core18
icon: snap/gui/qt5-application.png

apps:
  qt5-qml-application:
    environment:
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3    
    command: desktop-launch qmlapplication
  #  environment:
  #    LD_LIBRARY_PATH: $SNAP/opt/qt512/lib:$LD_LIBRARY_PATH
    plugs: [unity7, home]

parts:
  qmlapplication:
    source: src/
    plugin: qmakeppa
    after: [desktop-qt5]
    options: ["CONFIG+=my_option"]

  ppa:
    plugin: nil
    override-pull: |
      add-apt-repository -yu ppa:beineri/opt-qt-5.12.6-bionic
      apt install -y qt512-meta-full
      QT_BASE_DIR=/opt/qt512
      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export LD_LIBRARY_PATH=$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
      export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

  desktop-qt5:
    source: https://github.com/spompelio/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    after: [ppa]
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - dpkg-dev
      - qt512-meta-full
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - qt512base
      - qt512quickcontrols
      - qt512quickcontrols2
      - libgdk-pixbuf2.0-0
      - qt512svg # for loading icon themes which are svg
      - locales-all
      - xdg-user-dirs
      - libgtk2.0-0

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
